#ifndef CENTRE_VERSION_STRING
#define CENTRE_VERSION_STRING "v0.1.2-b"
#endif
#ifndef NETCDF_VERSION_STRING
#define NETCDF_VERSION_STRING "v4.7.3"
#define NETCDF_VERSION_STRLEN 6
#endif
#ifndef CENTRE_INTERNAL_VERSION
#define CENTRE_INTERNAL_VERSION "v0.1.2"
#endif
