#ifndef CENTRE_VERSION_STRING
#define CENTRE_VERSION_STRING "V0.1.0"
#endif
#ifndef NETCDF_VERSION_STRING
#define NETCDF_VERSION_STRING "V0.0.1"
#define NETCDF_VERSION_STRLEN 6
#endif
#ifndef CENTRE_INTERNAL_VERSION
#define CENTRE_INTERNAL_VERSION "V0.1.0"
#endif
